avalible = { -- ...to download
    --"Scrap", -- was used for testing
    --["Scrap"]={["url"]="https://towerofnix.github.io/scrap-mod/",["defold"]="2.0",["Scratch"]="https://scratch.mit.edu/discuss/topic/229671/"},
    "Adacraft",
    ["Adacraft"]={["url"]="https://www.adacraft.org/",["Scratch"]="https://scratch.mit.edu/discuss/topic/450114/",["defold"]="3.0"},
    
    "Bingo",
    ["Bingo"]={["url"]="https://bingo.futuresight.org/",["defold"]="1.x",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=37734"},
    "BYOB",
    ["BYOB"]={["url"]="https://snap.berkeley.edu/old_site/old-byob.html",["defold"]="1.x"},
    "BlockSoftDev",
    ["BlockSoftDev"]={["url"]="https://drive.google.com/file/d/1Xag9GI5mLxnrOL6qPxKRZmEPvBeAdlaQ/view",["Scratch"]="https://scratch.mit.edu/discuss/topic/493417/",["defold"]="1.x"},
    "Blue",
    ["Blue"]={["url"]="https://github.com/GRA0007/Blue/",["Scratch"]="https://scratch.mit.edu/discuss/topic/51366/",["defold"]="2.0"},
    "Bones",
    ["Bones"]={["url"]="https://bonesprogramming.weebly.com/",["defold"]="1.x"},
    "Botch GUI",
    ["Botch GUI"]={["url"]="https://coderdojotrento.github.io/botch-gui/master/",["defold"]="3.0"},
    "Branch Blocks",
    ["Branch Blocks"]={["url"]="https://branchblocks.weebly.com/",["Scratch"]="https://scratch.mit.edu/discuss/topic/8437/",["defold"]="1.x"},
    "blook",
    ["blook"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=107285",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=107285",["defold"]="1.x"},
    "Blockode",
    ["Blockode"]={["url"]="http://ericdutra.com/blockode.html",["defold"]="1.x"},
    "Box2D",
    ["Box2D"]={["url"]="https://griffpatch.github.io/scratch-gui/",["defold"]="3.0"},

    "Catch!",
    ["Catch!"]={["url"]="https://sourceforge.net/projects/catchscratchmod/",["defold"]="1.x"},
    "Chirp",
    ["Chirp"]={["url"]="https://web.archive.org/web/20131214022852/http://chirp.scratchr.org/",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=3779",["defold"]="1.x"},
    "Claook",
    ["Claook"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=45115",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=45115",["defold"]="1.x"},
    "Claw",
    ["Claw"]={["url"]="http://www.mediafire.com/?vb48st1mc3huvom",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=60902",["defold"]="1.x"},
    "ClipCC",
    ["ClipCC"]={["url"]="https://codingclip.com/editor/canary/",["Scratch"]="https://scratch.mit.edu/discuss/topic/557929/",["defold"]="3.0"},
    "Code X",
    ["Code X"]={["url"]="https://sites.google.com/site/codexscratchmod/",["Scratch"]="https://scratch.mit.edu/discuss/topic/120022/",["defold"]="2.0"},

    "Dream",
    ["Dream"]={["url"]="https://sites.google.com/site/dreamodscratch/home",["Scratch"]="https://scratch.mit.edu/discuss/topic/6498/",["defold"]="1.x"},
    "Draft 3.0",
    ["Draft 3.0"]={["url"]="https://scratch.mit.edu/discuss/topic/391360",["Scratch"]="https://scratch.mit.edu/discuss/topic/391360",["defold"]="3.0"},
    "DevBlocks",
    ["DevBlocks"]={["url"]="https://dev-blocks.powerbox1000.repl.co/",["defold"]="3.0"},

    "Enchanting",
    ["Enchanting"]={["url"]="http://enchanting.robotclub.ab.ca/",["defold"]="1.x"},
    "EV3 Classroom",
    ["EV3 Classroom"]={["url"]="https://education.lego.com/en-us/downloads/mindstorms-ev3/software"},
    "Explore",
    ["Explore"]={["url"]="http://explore-programming.weebly.com/",["Scratch"]="https://scratch.mit.edu/discuss/topic/8314/",["defold"]="1.x"},
    "E羊icques",
    ["E羊icques"]={["url"]="https://sheeptester.github.io/scratch-gui/",["defold"]="3.0"},

    "Fission",
    ["Fission"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59464",["defold"]="1.x"},
    "Float",
    ["Float"]={["url"]="https://github.com/dkter/float",["Scratch"]="https://scratch.mit.edu/discuss/topic/35059/?page",["defold"]="2.0"},

    "Gabmod",
    ["Gabmod"]={["url"]="https://scratch.mit.edu/discuss/topic/196336",["Scratch"]="https://scratch.mit.edu/discuss/topic/196336",["defold"]="1.x"},
    "Gamepad",
    ["Gamepad"]={["url"]="https://uchiwafuujinn.github.io/scratch3webmidi/",["defold"]="3.0"},
    "Gandi",
    ["Gandi"]={["url"]="https://cocrea.world/gandi",["Scratch"]="https://scratch.mit.edu/discuss/topic/617621/",["defold"]="3.0"},
    "Ghost",
    ["Ghost"]={["url"]="https://www.mediafire.com/?87bgwae2d4zrq77",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59758",["defold"]="1.x"},
    "gifblocks",
    ["gifblocks"]={["url"]="https://kach.github.io/gifblocks/",["defold"]="2.0"},
    "Gingerline",
    ["Gingerline"]={["url"]="https://drive.google.com/file/d/0BxUGjFM7MSFcbDJfSHBxdC1Hd1k/view?resourcekey=0-TlRBl8qa0SYjyimZ61jjFw",["Scratch"]="https://scratch.mit.edu/discuss/topic/58902/",["defold"]="2.0"},
    "Gopher",
    ["Gopher"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=66268",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=66268",["defold"]="1.x"},
    "Golucky",
    ["Golucky"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=110028",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=110028",["defold"]="1.x"},
    "Gloop",
    ["Gloop"]={["url"]="https://gloopprogramming.weebly.com/",["defold"]="1.x"},
    "GP",
    ["GP"]={["url"]="https://gpblocks.org/",["Scratch"]="https://en.scratch-wiki.info/wiki/GP_(programming_language)"},
    "Gvbvdxx",
    ["Gvbvdxx"]={["url"]="https://jasonglenevans.github.io/GMSource/",["defold"]="3.0"},
    "Gvbvdxx 2",
    ["Gvbvdxx 2"]={["url"]="https://jasonglenevans.github.io/GvbvdxxMod2/",["Scratch"]="https://scratch.mit.edu/discuss/topic/608180/",["defold"]="3.0"},

    "HopFoot",
    ["HopFoot"]={["url"]="https://www.dropbox.com/s/3o5hot1wytu9qhl/HopFoot%20V1.swf?dl=0",["Scratch"]="https://scratch.mit.edu/discuss/topic/191569",["defold"]="2.0"},

    "Insanity",
    ["Insanity"]={["url"]="http://insanity.jvvgindustries.com/",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=108085",["defold"]="1.x"},

    "JNXT",
    ["JNXT"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=55165",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=55165",["defold"]="1.x"}
,
    "Kitcat",
    ["Kitcat"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59463",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59463",["defold"]="1.x"},

    "Line",
    ["Line"]={["url"]="https://www.mediafire.com/file/m21nnw25jmm/Line1.0.image/file",["defold"]="1.x"},
    "Lion",
    ["Lion"]={["url"]="https://www.mediafire.com/file/wi4g5ulu9ix8xhw/Lion_Setup.exe/file/",["defold"]="1.x"},
    "LogoBlox",
    ["LogoBlox"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=62996",["defold"]="1.x"},
    "Lring",
    ["Lring"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=50401",["defold"]="1.x"},

    "M30W",
    ["M30W"]={["url"]="https://sourceforge.net/projects/m30w/",["Scratch"]="https://scratch.mit.edu/discuss/topic/7679/"},
    "Machine Learning for Kids",
    ["Machine Learning for Kids"]={["url"]="https://scratch.machinelearningforkids.co.uk/",["defold"]="3.0"},
    "Material Inc.",
    ["Material Inc."]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=37115",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=37115",["defold"]="1.x"},
    "Meow",
    ["Meow"]={["url"]="http://meowprogramming.weebly.com/",["defold"]="1.x"},
    "Mindstorms Robot Inventor Software",
    ["Mindstorms Robot Inventor Software"]={["url"]="https://www.lego.com/en-us/service/device-guide/mindstorms-robot-inventor/"},

    "Net Scratch",
    ["Net Scratch"]={["url"]="https://en.scratch-wiki.info/wiki/Net_Scratch",["Scratch"]="https://en.scratch-wiki.info/wiki/Net_Scratch",["defold"]="1.x"},

    "Open Blocks CC",
    ["Open Blocks CC"]={["url"]="https://openblockcc.github.io/openblock-gui/develop/",["defold"]="3.0"},

    "Playtime",
    ["Playtime"]={["url"]="https://playtime-scratchmod.weebly.com/",["Scratch"]="https://scratch.mit.edu/discuss/topic/126498/",["defold"]="1.x"},
    "Panther",
    ["Panther"]={["url"]="http://pantherprogramming.weebly.com/",["Scratch"]="https://en.scratch-wiki.info/wiki/Panther_(Scratch_modification)",["defold"]="1.x"},
    "Peak",
    ["Peak"]={["url"]="https://peakprogramming.weebly.com/",["defold"]="1.x"},
    "Peck",
    ["Peck"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=35284",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=35284",["defold"]="1.x"},
    "PenguinMod",
    ["PenguinMod"]={["url"]="https://penguinmod.github.io/PenguinMod-Gui/editor.html",["Scratch"]="https://scratch.mit.edu/discuss/topic/636814/",["defold"]="3.0"},

    "QUERTY 2",
    ["QUERTY 2"]={["url"]="https://www.dropbox.com/s/kyxiytezqcg241n/Scratch.swf",["Scratch"]="https://scratch.mit.edu/discuss/topic/182054/",["defold"]="2.0"}
}