avalible = { -- ...to download
    --"Scrap", -- was used for testing
    --["Scrap"]={["url"]="https://towerofnix.github.io/scrap-mod/",["defold"]="2.0",["Scratch"]="https://scratch.mit.edu/discuss/topic/229671/"},
    "Adacraft",
    ["Adacraft"]={["url"]="https://www.adacraft.org/",["Scratch"]="https://scratch.mit.edu/discuss/topic/450114/",["defold"]="3.0"},
    
    "Bingo",
    ["Bingo"]={["url"]="https://bingo.futuresight.org/",["defold"]="1.x",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=37734"},
    "BYOB",
    ["BYOB"]={["url"]="https://snap.berkeley.edu/old_site/old-byob.html",["defold"]="1.x"},
    "BlockSoftDev",
    ["BlockSoftDev"]={["url"]="https://drive.google.com/file/d/1Xag9GI5mLxnrOL6qPxKRZmEPvBeAdlaQ/view",["Scratch"]="https://scratch.mit.edu/discuss/topic/493417/",["defold"]="1.x"},
    "Blue",
    ["Blue"]={["url"]="https://github.com/GRA0007/Blue/",["Scratch"]="https://scratch.mit.edu/discuss/topic/51366/",["defold"]="2.0"},
    "Bones",
    ["Bones"]={["url"]="https://bonesprogramming.weebly.com/",["defold"]="1.x"},
    "Botch GUI",
    ["Botch GUI"]={["url"]="https://coderdojotrento.github.io/botch-gui/master/",["defold"]="3.0"},
    "Branch Blocks",
    ["Branch Blocks"]={["url"]="https://branchblocks.weebly.com/",["Scratch"]="https://scratch.mit.edu/discuss/topic/8437/",["defold"]="1.x"},
    "blook",
    ["blook"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=107285",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=107285",["defold"]="1.x"},
    "Blockode",
    ["Blockode"]={["url"]="http://ericdutra.com/blockode.html",["defold"]="1.x"},
    "Blocktalk",
    ["Blocktalk"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=42427",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=42427",["defold"]="1.x"},
    "Box2D",
    ["Box2D"]={["url"]="https://griffpatch.github.io/scratch-gui/",["defold"]="3.0"},

    "Catch!",
    ["Catch!"]={["url"]="https://sourceforge.net/projects/catchscratchmod/",["defold"]="1.x"},
    "Chirp",
    ["Chirp"]={["url"]="https://web.archive.org/web/20131214022852/http://chirp.scratchr.org/",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=3779",["defold"]="1.x"},
    "Claook",
    ["Claook"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=45115",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=45115",["defold"]="1.x"},
    "Claw",
    ["Claw"]={["url"]="http://www.mediafire.com/?vb48st1mc3huvom",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=60902",["defold"]="1.x"},
    "ClipCC",
    ["ClipCC"]={["url"]="https://codingclip.com/editor/canary/",["Scratch"]="https://scratch.mit.edu/discuss/topic/557929/",["defold"]="3.0"},
    "Code X",
    ["Code X"]={["url"]="https://sites.google.com/site/codexscratchmod/",["Scratch"]="https://scratch.mit.edu/discuss/topic/120022/",["defold"]="2.0"},

    "Dream",
    ["Dream"]={["url"]="https://sites.google.com/site/dreamodscratch/home",["Scratch"]="https://scratch.mit.edu/discuss/topic/6498/",["defold"]="1.x"},
    "Draft 3.0",
    ["Draft 3.0"]={["url"]="https://scratch.mit.edu/discuss/topic/391360",["Scratch"]="https://scratch.mit.edu/discuss/topic/391360",["defold"]="3.0"},
    "DevBlocks",
    ["DevBlocks"]={["url"]="https://dev-blocks.powerbox1000.repl.co/",["defold"]="3.0"},

    "Enchanting",
    ["Enchanting"]={["url"]="http://enchanting.robotclub.ab.ca/",["defold"]="1.x"},
    "EV3 Classroom",
    ["EV3 Classroom"]={["url"]="https://education.lego.com/en-us/downloads/mindstorms-ev3/software"},
    "Explore",
    ["Explore"]={["url"]="http://explore-programming.weebly.com/",["Scratch"]="https://scratch.mit.edu/discuss/topic/8314/",["defold"]="1.x"},
    "E羊icques",
    ["E羊icques"]={["url"]="https://sheeptester.github.io/scratch-gui/",["defold"]="3.0"},

    "Fission",
    ["Fission"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59464",["defold"]="1.x"},
    "Float",
    ["Float"]={["url"]="https://github.com/dkter/float",["Scratch"]="https://scratch.mit.edu/discuss/topic/35059/?page",["defold"]="2.0"},

    "Gabmod",
    ["Gabmod"]={["url"]="https://scratch.mit.edu/discuss/topic/196336",["Scratch"]="https://scratch.mit.edu/discuss/topic/196336",["defold"]="1.x"},
    "Gamepad",
    ["Gamepad"]={["url"]="https://uchiwafuujinn.github.io/scratch3webmidi/",["defold"]="3.0"},
    "Gandi",
    ["Gandi"]={["url"]="https://cocrea.world/gandi",["Scratch"]="https://scratch.mit.edu/discuss/topic/617621/",["defold"]="3.0"},
    "Ghost",
    ["Ghost"]={["url"]="https://www.mediafire.com/?87bgwae2d4zrq77",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59758",["defold"]="1.x"},
    "gifblocks",
    ["gifblocks"]={["url"]="https://kach.github.io/gifblocks/",["defold"]="2.0"},
    "Gingerline",
    ["Gingerline"]={["url"]="https://drive.google.com/file/d/0BxUGjFM7MSFcbDJfSHBxdC1Hd1k/view?resourcekey=0-TlRBl8qa0SYjyimZ61jjFw",["Scratch"]="https://scratch.mit.edu/discuss/topic/58902/",["defold"]="2.0"},
    "Gopher",
    ["Gopher"]={["url"]="http://medianet.weebly.com/",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=66268",["defold"]="1.x"},
    "Golucky",
    ["Golucky"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=110028",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=110028",["defold"]="1.x"},
    "Gloop",
    ["Gloop"]={["url"]="https://gloopprogramming.weebly.com/",["defold"]="1.x"},
    "GP",
    ["GP"]={["url"]="https://gpblocks.org/",["Scratch"]="https://en.scratch-wiki.info/wiki/GP_(programming_language)"},
    "Gvbvdxx",
    ["Gvbvdxx"]={["url"]="https://jasonglenevans.github.io/GMSource/",["defold"]="3.0"},
    "Gvbvdxx 2",
    ["Gvbvdxx 2"]={["url"]="https://jasonglenevans.github.io/GvbvdxxMod2/",["Scratch"]="https://scratch.mit.edu/discuss/topic/608180/",["defold"]="3.0"},

    "HopFoot",
    ["HopFoot"]={["url"]="https://www.dropbox.com/s/3o5hot1wytu9qhl/HopFoot%20V1.swf?dl=0",["Scratch"]="https://scratch.mit.edu/discuss/topic/191569",["defold"]="2.0"},

    "Insanity",
    ["Insanity"]={["url"]="http://insanity.jvvgindustries.com/",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=108085",["defold"]="1.x"},

    "JNXT",
    ["JNXT"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=55165",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=55165",["defold"]="1.x"}
,
    "Kitcat",
    ["Kitcat"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59463",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59463",["defold"]="1.x"},

    "Line",
    ["Line"]={["url"]="https://www.mediafire.com/file/m21nnw25jmm/Line1.0.image/file",["defold"]="1.x"},
    "Lion",
    ["Lion"]={["url"]="https://www.mediafire.com/file/wi4g5ulu9ix8xhw/Lion_Setup.exe/file/",["defold"]="1.x"},
    "LogoBlox",
    ["LogoBlox"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=62996",["defold"]="1.x"},
    "Lring",
    ["Lring"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=50401",["defold"]="1.x"},

    "M30W",
    ["M30W"]={["url"]="https://sourceforge.net/projects/m30w/",["Scratch"]="https://scratch.mit.edu/discuss/topic/7679/"},
    "Machine Learning for Kids",
    ["Machine Learning for Kids"]={["url"]="https://scratch.machinelearningforkids.co.uk/",["defold"]="3.0"},
    "Material Inc.",
    ["Material Inc."]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=37115",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=37115",["defold"]="1.x"},
    "Meow",
    ["Meow"]={["url"]="http://meowprogramming.weebly.com/",["defold"]="1.x"},
    "Mindstorms Robot Inventor Software",
    ["Mindstorms Robot Inventor Software"]={["url"]="https://www.lego.com/en-us/service/device-guide/mindstorms-robot-inventor/"},

    "Net Scratch",
    ["Net Scratch"]={["url"]="https://en.scratch-wiki.info/wiki/Net_Scratch",["Scratch"]="https://en.scratch-wiki.info/wiki/Net_Scratch",["defold"]="1.x"},

    "Open Blocks CC",
    ["Open Blocks CC"]={["url"]="https://openblockcc.github.io/openblock-gui/develop/",["defold"]="3.0"},

    "Playtime",
    ["Playtime"]={["url"]="https://playtime-scratchmod.weebly.com/",["Scratch"]="https://scratch.mit.edu/discuss/topic/126498/",["defold"]="1.x"},
    "Panther",
    ["Panther"]={["url"]="http://pantherprogramming.weebly.com/",["Scratch"]="https://en.scratch-wiki.info/wiki/Panther_(Scratch_modification)",["defold"]="1.x"},
    "Peak",
    ["Peak"]={["url"]="https://peakprogramming.weebly.com/",["defold"]="1.x"},
    "Peck",
    ["Peck"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=35284",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=35284",["defold"]="1.x"},
    "PenguinMod",
    ["PenguinMod"]={["url"]="https://penguinmod.github.io/PenguinMod-Gui/editor.html",["Scratch"]="https://scratch.mit.edu/discuss/topic/636814/",["defold"]="3.0"},

    "QUERTY 2",
    ["QUERTY 2"]={["url"]="https://www.dropbox.com/s/kyxiytezqcg241n/Scratch.swf",["Scratch"]="https://scratch.mit.edu/discuss/topic/182054/",["defold"]="2.0"},

    "RAGE",
    ["RAGE"]={["url"]="https://www.mediafire.com/file/5qvmbwmvp3kr4nl/Rage_1.3.1.zip/file/",["defold"]="1.x"},
    "Rocket",
    ["Rocket"]={["url"]="https://www.mediafire.com/file/x1iku1vc2j2w5le/Rocket_0.3.zip/file",["defold"]="1.x"},

    "S1mple",
    ["S1mple"]={["url"]="http://modscratch.weebly.com/downloads.html",["Scratch"]="https://scratch.mit.edu/discuss/topic/103094/",["defold"]="1.x"},
    "Shiro",
    ["Shiro"]={["url"]="https://drive.google.com/file/d/1yWC56rx2Mpnr3755is2pFv4ccEr2i-tt/view",["Scratch"]="https://scratch.mit.edu/discuss/topic/421559/",["defold"]="1.x"},
    "Scat",
    ["Scat"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59663",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=59663",["defold"]="1.x"},
    "Scrap", -- was used for testing
    ["Scrap"]={["url"]="https://towerofnix.github.io/scrap-mod/",["defold"]="2.0",["Scratch"]="https://scratch.mit.edu/discuss/topic/229671/"},
    "Scratch 3.0 Anaorodrigues (With ScratchJr)",
    ["Scratch 3.0 Anaorodrigues (With ScratchJr)"]={["url"]="https://anaorodrigues.github.io/scratch-gui/",["defold"]="3.0"},
    "Scratch 3.0 Robot Operating System",
    ["Scratch 3.0 Robot Operating System"]={["url"]="https://scratch3-ros.jsk.imi.i.u-tokyo.ac.jp/",["defold"]="3.0"},
    "Scratch CE",
    ["Scratch CE"]={["url"]="https://scratchce.github.io/beta/0.5.1/",["defold"]="3.0"},
    "Scratch Advanced",
    ["Scratch Advanced"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=67807",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=67807",["defold"]="1.x"},
    "Scratch for Second Life", --didnt found any better links...
    ["Scratch for Second Life"]={["url"]="https://www.youtube.com/watch?v=srOM7uYuRDg",["Scratch"]="https://en.scratch-wiki.info/wiki/Scratch_for_Second_Life",["defold"]="1.x"},
    "Scratch Ohbot",
    ["Scratch Ohbot"]={["url"]="https://scratch.ohbot.co.uk/",["defold"]="3.0"},
    "Scratux",
    ["Scratux"]={["url"]="https://github.com/scratux/scratux",["defold"]="3.0"},
    "ScribbleBlox",
    ["ScribbleBlox"]={["url"]="http://jonathan50.github.io/scribbleblox-site/",["Scratch"]="https://scratch.mit.edu/discuss/topic/39898/",["defold"]="2.0"},
    "Scribe",
    ["Scribe"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=34015",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=34015",["defold"]="1.x"},
    "Sharp",
    ["Sharp"]={["url"]="http://sharpscratchmod.github.io/",["Scratch"]="https://scratch.mit.edu/discuss/topic/199192/",["defold"]="2.0"},
    "Shriek",
    ["Shriek"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=47086",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=47086",["defold"]="1.x"},
    "SLant",
    ["SLant"]={["url"]="https://sites.google.com/site/slwhizzer/",["defold"]="1.x"},
    "Scratch softDev SDK",
    ["Scratch softDev SDK"]={["url"]="https://www.mediafire.com/file/uw51sf7out12qza/Scratch%20softDev%20SDK.zip",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=20955",["defold"]="1.x"},
    "SpiderWeb",
    ["SpiderWeb"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=68306",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=68306",["defold"]="1.x"},
    "Spike Prime Software",
    ["Spike Prime Software"]={["url"]="https://education.lego.com/en-us/downloads/spike-app/software"},
    "Spiral",
    ["Spiral"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=64796",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=64796",["defold"]="1.x"},
    "Squirrel",
    ["Squirrel"]={["url"]="http://squirrelprogramming.weebly.com/",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=35131",["defold"]="1.x"},
    "Star Truss",
    ["Star Truss"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=41915&p=2",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=41915&p=2",["defold"]="1.x"},
    "Streak",
    ["Streak"]={["url"]="http://web.archive.org/web/20100903075459/http://streak.t35.com/downloads.html",["defold"]="1.x"},
    "Strech3",
    ["Strech3"]={["url"]="https://stretch3.github.io/",["defold"]="3.0"},
    "Swipe",
    ["Swipe"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=34734",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=34734",["defold"]="1.x"},

    "TaBS",
    ["TaBS"]={["url"]="https://tabs-scratch.eu.org/",["Scratch"]="https://scratch.mit.edu/discuss/topic/596216/",["defold"]="3.0"},
    "TACKLE",
    ["TACKLE"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=60504",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=60504",["defold"]="1.x"},
    "Theblocksmod",
    ["Theblocksmod"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=43815",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=43815",["defold"]="1.x"},
    "Tiger",
    ["Tiger"]={["url"]="https://sourceforge.net/projects/tigerscratchmod/",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=81604",["defold"]="1.x"},
    "TigerBuild",
    ["TigerBuild"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=116726",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=116726"},
    "tosh",
    ["tosh"]={["url"]="https://scratch.mit.edu/discuss/topic/192915/",["Scratch"]="https://en.scratch-wiki.info/wiki/Tosh_(Scratch_modification)",["defold"]="2.0"},
    "Turbowarp",
    ["Turbowarp"]={["url"]="https://turbowarp.org",["Scratch"]="",["defold"]="3.0"},

    "Useful itch",
    ["Useful itch"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=52622",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=52622",["defold"]="1.x"},

    "Web Blox",
    ["Web Blox"]={["url"]="http://web-blox.weebly.com/",["Scratch"]="https://en.scratch-wiki.info/wiki/Web_Blox_(Scratch_modification)",["defold"]="1.x"},
    "Whiskers",
    ["Whiskers"]={["url"]="https://github.com/NoMod-Programming/Whiskers/",["Scratch"]="https://scratch.mit.edu/discuss/topic/157672/",["defold"]="2.0"},

    "Zambya",
    ["Zambya"]={["url"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=69381",["Scratch"]="https://scratcharchive.asun.co/forums/viewtopic.php?id=69381",["defold"]="1.x"},
    "Zing!",
    ["Zing!"]={["url"]="http://zingmod.weebly.com/",["defold"]="1.x"}
} --https://scratch.mit.edu/discuss/topic/588771/
curentv = {}
curentv.build = "2"
curentv.date = "11.12.2022"
